package utils;

public enum Header {
    ADD_CLIENT, REMOVE_CLIENT, UPDATE_CLIENT, GET_ALL_CLIENTS, GET_ALL_CLIENTS_BORN_BEFORE, ADD_LIST_OF_CLIENTS,
    ADD_GUN_PROVIDER, REMOVE_GUN_PROVIDER, UPDATE_GUN_PROVIDER, GET_ALL_GUN_PROVIDERS, GET_GUN_PROVIDER_BY_ID,
    ADD_GUN_TYPE, REMOVE_GUN_TYPE, UPDATE_GUN_TYPE, GET_ALL_GUN_TYPES, GET_GUN_TYPE_BY_ID, FILTER_BY_CATEGORY,
    ADD_RENTAL, REMOVE_RENTAL, UPDATE_RENTAL, GET_ALL_RENTALS


}
